<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Service\Data;

use Drago;
use Nette;

class RolesData extends Drago\Utils\ExtraArrayHash
{
	use Nette\SmartObject;

	public const ID = 'id';
	public const NAME = 'name';
	public const PARENT = 'parent';

	public int $id;
	public string $name;
	public string|int $parent;
}
