<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Privileges;

use Drago;


class PrivilegesEntity extends Drago\Database\Entity
{
	use PrivilegesMapper;

	public const Table = 'privileges';
	public const Id = 'id';
	public const Name = 'name';
}
