<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Privileges;


trait PrivilegesMapper
{
	public ?int $id;
	public string $name;
}
