<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Privileges;

use Drago;


class PrivilegesData extends Drago\Utils\ExtraArrayHash
{
	public const string
		ID = 'id',
		NAME = 'name';

	public ?int $id;
	public string $name;
}
