<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Resources;


trait ResourcesMapper
{
	public ?int $id;
	public string $name;
}
