<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Resources;

use Drago;
use Nette;


class ResourcesData extends Drago\Utils\ExtraArrayHash
{
	use ResourcesMapper;
}
