<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Resources;

use Drago;


class ResourcesEntity extends Drago\Database\Entity
{
	use ResourcesMapper;

	public const Table = 'resources';
	public const Id = 'id';
	public const Name = 'name';
}
