<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Resources;

use Drago;
use Nette;


class ResourcesEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;
	use ResourcesMapper;

	public const table = 'resources';
	public const id = 'id';
	public const name = 'name';
}
