<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Roles;

use Drago;


class RolesEntity extends Drago\Database\EntityOracle
{
	public const TABLE = 'ACL_ROLES';
	public const PRIMARY = 'ID';
	public const NAME = 'NAME';
	public const PARENT = 'PARENT';
	public const DESCRIPTION = 'DESCRIPTION';

	public ?int $id;
	public string $name;
	public string|int $parent;
	public ?string $description;
}
