<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Roles;

use Drago;


class RolesEntity extends Drago\Database\Entity
{
	use RolesMapper;

	public const Table = 'roles';
	public const PrimaryKey = 'id';
	public const ColumnName = 'name';
	public const ColumnParent = 'parent';
}
