<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Roles;

use Drago;


class RolesData extends Drago\Utils\ExtraArrayHash
{
	public const string
		ID = 'id',
		NAME = 'name',
		PARENT = 'parent',
		DESCRIPTION = 'description';

	public ?int $id;
	public string $name;
	public string|int $parent;
	public ?string $description;
}
