<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Roles;

use Drago;
use Nette;


class RolesEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;
	use RolesMapper;

	public const table = 'roles';
	public const id = 'id';
	public const name = 'name';
	public const parent = 'parent';
}
