<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Roles;


trait RolesMapper
{
	public ?int $id;
	public string $name;
	public string|int $parent;
}
