<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;
use Nette;


class PermissionsViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const table = 'permissions_view';
	public const id = 'id';
	public const resource = 'resource';
	public const privilege = 'privilege';
	public const role = 'role';
	public const allowed = 'allowed';

	public int $id;
	public ?string $resource = null;
	public ?string $privilege = null;
	public ?string $role = null;
	public int $allowed;
}
