<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;
use Nette;


class PermissionsData extends Drago\Utils\ExtraArrayHash
{
	use PermissionsMapper;
}
