<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;


class PermissionsViewEntity extends Drago\Database\EntityOracle
{
	public const string
		TABLE = 'ACL_PERMISSIONS_VIEW',
		ID = 'ID',
		RESOURCE = 'RESOURCE',
		PRIVILEGE = 'PRIVILEGE',
		ROLE = 'ROLE',
		ALLOWED = 'ALLOWED';

	public int $id;
	public ?string $resource = null;
	public ?string $privilege = null;
	public ?string $role = null;
	public int $allowed;
}
