<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;
use Nette;


class PermissionsRolesViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const table = 'permissions_roles_view';
	public const id = 'id';
	public const name = 'name';
	public const parent = 'parent';

	public int $id;
	public string $name;
	public int $parent;
}
