<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;
use Nette;


class PermissionsViewEntity extends Drago\Database\EntityOracle
{
	use Nette\SmartObject;

	public const TABLE = 'ACL_PERMISSIONS_VIEW';
	public const ID = 'ID';
	public const RESOURCE = 'RESOURCE';
	public const PRIVILEGE = 'PRIVILEGE';
	public const ROLE = 'ROLE';
	public const ALLOWED = 'ALLOWED';

	public int $id;
	public ?string $resource = null;
	public ?string $privilege = null;
	public ?string $role = null;
	public int $allowed;
}
