<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;


class PermissionsEntity extends Drago\Database\EntityOracle
{
	public const string
		TABLE = 'ACL_PERMISSIONS',
		PRIMARY = 'ID',
		ROLE_ID = 'ROLE_ID',
		RESOURCE_ID = 'RESOURCE_ID',
		PRIVILEGE_ID = 'PRIVILEGE_ID',
		ALLOWED = 'ALLOWED';

	public ?int $id;
	public int $role_id;
	public int $resource_id;
	public int $privilege_id;
	public int $allowed;
}
