<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;
use Nette;


class PermissionsRolesViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const TABLE = 'ACL_PERMISSIONS_ROLES_VIEW';
	public const ID = 'ID';
	public const NAME = 'NAME';
	public const PARENT = 'PARENT';

	public int $id;
	public string $name;
	public int $parent;
}
