<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;


class PermissionsEntity extends Drago\Database\Entity
{
	use PermissionsMapper;

	public const Table = 'permissions';
	public const PrimaryKey = 'id';
	public const ColumnRoleId = 'role_id';
	public const ColumnResourceId = 'resource_id';
	public const ColumnPrivilegeId = 'privilege_id';
	public const ColumnAllowed = 'allowed';
}
