<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;


class PermissionsRolesViewEntity extends Drago\Database\EntityOracle
{
	public const string
		TABLE = 'ACL_PERMISSIONS_ROLES_VIEW',
		ID = 'ID',
		NAME = 'NAME',
		PARENT = 'PARENT';

	public int $id;
	public string $name;
	public int $parent;
}
