<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;


class PermissionsEntity extends Drago\Database\EntityOracle
{
	public const TABLE = 'ACL_PERMISSIONS';
	public const PRIMARY = 'ID';
	public const ROLE_ID = 'ROLE_ID';
	public const RESOURCE_ID = 'RESOURCE_ID';
	public const PRIVILEGE_ID = 'PRIVILEGE_ID';
	public const ALLOWED = 'ALLOWED';

	public ?int $id;
	public int $role_id;
	public int $resource_id;
	public int $privilege_id;
	public int $allowed;
}
