<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Permissions;

use Drago;


class PermissionsData extends Drago\Utils\ExtraArrayHash
{
	public const string
		ID = 'id',
		ROLE_ID = 'role_id',
		RESOURCE_ID = 'resource_id',
		PRIVILEGE_ID = 'privilege_id',
		ALLOWED = 'allowed';

	public ?int $id;
	public int $role_id;
	public int $resource_id;
	public int $privilege_id;
	public int $allowed;
}
