<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Service\Entity;

use Drago;
use Nette;

class PermissionsRolesViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const TABLE = 'permissions_roles_view';
	public const ID = 'id';
	public const NAME = 'name';
	public const PARENT = 'parent';

	public int $id;
	public string $name;
	public int $parent;
}
