<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Service\Entity;

use Drago;
use Nette;

class PermissionsViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const TABLE = 'permissions_view';
	public const ID = 'id';
	public const RESOURCE = 'resource';
	public const PRIVILEGE = 'privilege';
	public const ROLE = 'role';
	public const ALLOWED = 'allowed';

	public int $id;
	public ?string $resource = null;
	public ?string $privilege = null;
	public ?string $role = null;
	public int $allowed;
}
