<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Service\Entity;

use Drago;
use Nette;

class ResourcesEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const TABLE = 'resources';
	public const PRIMARY = 'id';
	public const NAME = 'name';

	public int $id;
	public string $name;
}
