<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Service\Entity;

use Drago;
use Nette;

class UsersRolesViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const TABLE = 'users_roles_view';
	public const USER_ID = 'user_id';
	public const USERNAME = 'username';
	public const ROLE = 'role';

	public ?int $user_id = null;
	public ?string $username = null;
	public string|array|null $role = null;
}
