<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace App\Entity;

use Drago;
use Nette;

class AuthorizationViewEntity extends Drago\Database\EntityOracle
{
	use Nette\SmartObject;

	public const TABLE = 'authorization_view';
	public const ROLE = 'role';

	public ?string $role = null;
}
