<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Entity;

use Drago;
use Nette;

class PrivilegesEntity extends Drago\Database\EntityOracle
{
	use Nette\SmartObject;

	public const TABLE = 'privileges';
	public const PRIMARY = 'id';
	public const NAME = 'name';

	public int $id;
	public string $name;
}
