<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Entity;

use Drago;
use Nette;

class UsersRolesViewEntity extends Drago\Database\EntityOracle
{
	use Nette\SmartObject;

	public const TABLE = 'users_roles_view';
	public const ROLE = 'role';

	public ?string $role = null;
}
