<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;
use Nette;


class AccessEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const table = 'users';
	public const id = 'id';
	public const username = 'username';

	public ?int $id;
	public string $username;
}
