<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;


class AccessEntity extends Drago\Database\Entity
{
	public const Table = 'users';
	public const PrimaryKey = 'id';
	public const ColumnUsername = 'username';

	public ?int $id;
	public string $username;
}
