<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;
use Nette;


class AccessRolesEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const table = 'users_roles';
	public const roleId = 'role_id';
	public const userId = 'user_id';

	public int $role_id;
	public int $user_id;
}
