<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;
use Nette;


class AccessRolesViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const Table = 'users_roles_view';
	public const UserId = 'user_id';
	public const Username = 'username';
	public const Role = 'role';

	public ?int $user_id = null;
	public ?string $username = null;
	public string|array|null $role = null;
}
