<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;


/**
 * Data class for Access roles.
 */
class AccessRolesData extends Drago\Utils\ExtraArrayHash
{
	// Constant for the ID field
	public const string Id = 'id';

	// Array of role IDs associated with the user
	public array $role_id;

	// User ID the roles are associated with
	public ?int $user_id;

	// ID of the role data record
	public ?int $id;
}
