<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;


class AccessRolesEntity extends Drago\Database\Entity
{
	public const Table = 'users_roles';
	public const ColumnRoleId = 'role_id';
	public const ColumnUserId = 'user_id';

	public int $role_id;
	public int $user_id;
}
