<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;
use Nette;


class AccessRolesData extends Drago\Utils\ExtraArrayHash
{
	use Nette\SmartObject;

	public const id = 'id';

	public array $role_id;
	public ?int $user_id;
	public ?int $id;
}
