<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;


class DepartmentsEntity extends Drago\Database\EntityOracle
{
	public const TABLE = 'DEPARTMENTS';
	public const PRIMARY = 'ID';
	public const USERNAME = 'NAME';
	public ?int $id;
	public string $name;
}
