<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;


class UsersDepartmentsEntity extends Drago\Database\EntityOracle
{
	public const string
		TABLE = 'USERS_DEPARTMENTS',
		PRIMARY = 'ID',
		USER_ID = 'USER_ID',
		DEPARTMENT_ID = 'DEPARTMENT_ID';

	public ?int $id;
	public int $user_id;
	public int $department_id;
}
