<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;


class UsersRolesViewEntity extends Drago\Database\EntityOracle
{
	public const string
		TABLE = 'USERS_ROLES_VIEW',
		USER_ID = 'USER_ID',
		USERNAME = 'USERNAME',
		ROLE = 'ROLE';

	public ?int $user_id = null;
	public ?string $username = null;
	public string|array|null $role = null;
}
