<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Control\Access;

use Drago;
use Nette;


class UsersRolesViewEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const TABLE = 'USERS_ROLES_VIEW';
	public const USER_ID = 'USER_ID';
	public const USERNAME = 'USERNAME';
	public const ROLE = 'ROLE';

	public ?int $user_id = null;
	public ?string $username = null;
	public string|array|null $role = null;
}
