<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace Drago\Authorization\Data;

use Drago;
use Nette;

class PrivilegesData extends Drago\Utils\ExtraArrayHash
{
	use Nette\SmartObject;

	public const ID = 'id';
	public const NAME = 'name';

	public int $id;
	public string $name;
}
